### ISSUE TITLE
Remaining UTxO-HD tasks for `v0.1-ready`

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/ouroboros-consensus#127]
- [x] Big changes: input-output-hk/ouroboros-consensus#43 
- [x] Small must-do changes: input-output-hk/ouroboros-consensus#149 
- [x] Successful run of ad-hoc benchmarks for replay and syncing (we should not detect any issues). input-output-hk/ouroboros-consensus#181
- [x] Tech-debt maybe-do items: input-output-hk/ouroboros-consensus#148
