### ISSUE TITLE
UTxO-HD tech-debt maybe-do items

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-consensus#148]
- Tests
    - [x] input-output-hk/ouroboros-network#4455 
    - [ ] input-output-hk/ouroboros-consensus#215 has to be investigated, perhaps it is not possible
    - [ ] input-output-hk/ouroboros-consensus#206 
    - [x] input-output-hk/ouroboros-consensus#111 
    - [ ] input-output-hk/ouroboros-consensus#204 
- Logic
    - [ ] input-output-hk/ouroboros-consensus#144 not sure if we want to do it. We have to check if it will introduce too many dead-code paths (as the error case is impossible in absence of Consensus bugs)
    - [ ] input-output-hk/ouroboros-consensus#207 
    - [ ] input-output-hk/ouroboros-consensus#208 
    - [ ] input-output-hk/ouroboros-consensus#210 
    - [x] input-output-hk/ouroboros-consensus#145 
- Docs
    - [ ] input-output-hk/ouroboros-consensus#209 
    - [ ] input-output-hk/ouroboros-consensus#211 A couple of diagrams explaining how this works would be nice. Explain why it has to be an automorphism (Telescope.expand requires it)
    - [ ] input-output-hk/ouroboros-consensus#216 
    - [x] input-output-hk/ouroboros-network#4314 
- Potential performance improvements
    - [x] input-output-hk/ouroboros-network#4444

**Comment by dnadales** [comment]
Closed as now we have proper labelling.
