### ISSUE TITLE
Incorporate UTxO-HD improvements resulting from the refactoring

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-consensus#149]
- Public API
    - [x] input-output-hk/ouroboros-consensus#98
    - [x] input-output-hk/ouroboros-consensus#97
    - [x] input-output-hk/ouroboros-network#4373 
    - [x] input-output-hk/ouroboros-consensus#57 
- Internal
    - [x] input-output-hk/ouroboros-consensus#52 
    - [x] input-output-hk/ouroboros-consensus#99 The way this module works has to be improved. Using newtypes for before and after? Better combinators?
    - [x] input-output-hk/ouroboros-network#4543
- Components
    - [x] input-output-hk/ouroboros-network#4458
